### ISSUE TITLE
Compile error due to pybind11

### ISSUE THREAD

**Issue by rty813** [ros2/orocos_kdl_vendor#22]
```
--- stderr: python_orocos_kdl_vendor                                                                                                                                                                                     
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/PyKDL.cpp:32:16: error: expected constructor, destructor, or type conversion before '(' token
 PYBIND11_MODULE(PyKDL, m)
                ^
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/frames.cpp: In function 'void init_frames(pybind11::module&)':
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/frames.cpp:95:20: error: 'pickle' is not a member of 'py'
     vector.def(py::pickle(
                    ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/frames.cpp:170:20: error: 'pickle' is not a member of 'py'
     wrench.def(py::pickle(
                    ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/frames.cpp:244:19: error: 'pickle' is not a member of 'py'
     twist.def(py::pickle(
                   ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/framevel.cpp: In function 'void init_framevel(pybind11::module&)':
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/framevel.cpp:139:24: error: 'pickle' is not a member of 'py'
     vector_vel.def(py::pickle(
                        ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/framevel.cpp:224:23: error: 'pickle' is not a member of 'py'
     twist_vel.def(py::pickle(
                       ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/frames.cpp:372:22: error: 'pickle' is not a member of 'py'
     rotation.def(py::pickle(
                      ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/frames.cpp:453:19: error: 'pickle' is not a member of 'py'
     frame.def(py::pickle(
                   ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/framevel.cpp:308:26: error: 'pickle' is not a member of 'py'
     rotation_vel.def(py::pickle(
                          ^~~~~~
/opt/ros/humble/build/python_orocos_kdl_vendor/_deps/python_orocos_kdl-src/python_orocos_kdl/PyKDL/framevel.cpp:381:23: error: 'pickle' is not a member of 'py'
     frame_vel.def(py::pickle(
                       ^~~~~~
make[2]: *** [_deps/python_orocos_kdl-build/CMakeFiles/PyKDL.dir/PyKDL/PyKDL.cpp.o] Error 1
```

----

Pybind11 is a submodule of orocos_kinematics_dynamics. It's not initialized by default, so if you download it directly, the pybind11 directory will be empty.
![image](https://github.com/ros2/orocos_kdl_vendor/assets/22488813/363d0d2f-39ce-46e4-aa05-3c1cdb5ee904)
![image](https://github.com/ros2/orocos_kdl_vendor/assets/22488813/b33fd905-4b07-4f1f-a06a-bdc351040585)

**Comment by rty813** [comment]
Adding a note, I've already installed pybind11 using pip.

**Comment by clalancette** [comment]
> Adding a note, I've already installed pybind11 using pip.

This should not be installed with pip; we vendor it ourselves.  I would recommend uninstalling it.

> And, OS is ubuntu18.04

I'm just warning you now that this is going to be a long hard road to get Humble working on 18.04.  That is two releases earlier than it is targeting.

**Comment by sloretz** [comment]
Since [ROS Humble targets 22.04](https://www.ros.org/reps/rep-2000.html#humble-hawksbill-may-2022-may-2027), I'm going to close this.

 I'd recommend building it inside a 22.04 container. If you want to get it working in 18.04 you'll at the very least need to also build [pybind11_vendor](https://github.com/ros2/pybind11_vendor/tree/humble). ROS packages tend to use system versions of dependencies, or vendor packages when they're not available. Dependencies from git submodules aren't used as there wouldn't be a way to package them on the buildfarm.
